### GET all videos
POST http://localhost:8080/ask
Content-Type: application/json

{
  "question": "what are the videos offered by SivaLabs?"
}

### Search videos
POST http://localhost:8080/ask
Content-Type: application/json

{
  "question": "Give me the list of videos on Spring from SivaLabs?"
}

### Get video details by title
POST http://localhost:8080/ask
Content-Type: application/json

{
  "question": "Get more info on 'Spring Boot Microservices Complete Tutorial' video from SivaLabs?"
}
